### ISSUE TITLE
.coffee tests no longer show up when using ember-cli 0.2.0

### ISSUE THREAD

**Issue by elucid** [alexspeller/ember-cli-coffees6#8]
I'm just in the process of upgrading ember-cli to 0.2.0 and I've noticed that after updating the dependencies mentioned in the guide, my tests (which are all written in coffeescript) no longer get picked up by the test runner.

If I switch coffeescript compilation over to the ember-cli-coffeescript addon the tests get picked up but then everything breaks due to `error: reserved word "import"`

Has anyone ever seen this before? I'm going to keep digging but any guidance would be much appreciated.

**Comment by alexspeller** [comment]
Hi, sorry I've been travelling. I think that my addon is broken with the latest ember-cli, I've been waiting for an issue with ember-cli-coffeescript to be merged which I think it is now. Expect an update over the weekend :)

**Comment by elucid** [comment]
Thanks very much.

**Comment by devinrhode2** [comment]
Ah almost forgot about this issue. [We're focusing on the future of how es6 and coffeescript could better work together](https://github.com/babelscript/rfcs/pull/1#issuecomment-82606638), this addon is just a hack, the `error: reserved word "import"` is from coffeescript itself reserving the import/export keywords, which is why you need to escape import/exports with ember-cli-coffeescript like they have documented
```coffeescript
`import Em from 'ember';`
```
This should solve the issue, although the escaped import/export statements are ugly, language fragmentation is a bigger more ugly issue.

**Comment by alexspeller** [comment]
This should be fixed now

**Comment by devinrhode2** [comment]
Fixed! :D!
